# Setup
title:        Zhendong Ang
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Zhendong Ang
  url:        http://ang9876.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown